# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Audiobookshelf"
description: "A Home Assistant wrapper for Audiobookshelf (https://www.audiobookshelf.org)"
version: "1.0.0"
slug: "audiobookshelf"
init: false
arch:
  - aarch64
  - amd64
ports:
  80/tcp: 3080
image: "ghcr.io/advplyr/audiobookshelf:2.25.1"
