# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Audiobookshelf"
description: "A Home Assistant wrapper for Audiobookshelf (https://www.audiobookshelf.org)"
url: https://www.audiobookshelf.org/
version: "2.27.0"
slug: "audiobookshelf"
init: false
arch:
  - aarch64
  - amd64
ports:
  80/tcp: null
map:
  - type: addon_config
    read_only: false
    path: /config
  - type: media
  - type: data
    path: /metadata
    read_only: false
image: "ghcr.io/advplyr/audiobookshelf"
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
